name: Mi primer pipeline

on:
  push:
    branches:
      - "main"

jobs:
  saludo:
    name: Mi primer saludo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Mensaje en consola
        run: |
          echo "Saludo desde el mensaje 1"

  saludo2:
    name: Mi segundo saludo
    runs-on: ubuntu-latest
    needs: [saludo]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Mensaje en consola
        run: |
          echo "Saludo desde el mensaje 2"

  saludo3:
    name: Mi tercer saludo
    runs-on: ubuntu-latest
    needs: [saludo2]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Mensaje en consola
        run: |
          echo "Saludo desde el mensaje 3"